name: Daily GitHub Trending Job

on:
  schedule:
    - cron: '55 1 * * *'  # 每天UTC时间12:00（北京时间20:00）
  workflow_dispatch:
    inputs:
      date:
        description: 'Specific date to run (YYYY-MM-DD)'
        required: false

jobs:
  fetch-and-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Fetch trending repositories
      run: |
        if [ -n "${{ github.event.inputs.date }}" ]; then
          python scripts/fetch_stars.py --date ${{ github.event.inputs.date }}
        else
          python scripts/fetch_stars.py
        fi
        
    - name: Send email report
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
      run: |
        if [ -n "${{ github.event.inputs.date }}" ]; then
          echo "Skipping email for historical date"
        else
          python scripts/send_email.py
        fi
        
    - name: Generate webpage
      run: |
        if [ -n "${{ github.event.inputs.date }}" ]; then
          python scripts/generate_webpage.py --date ${{ github.event.inputs.date }}
        else
          python scripts/generate_webpage.py
        fi
        
    - name: Commit and push changes
      env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动提供的token
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git add .
        git commit -m "Update data and webpage for ${{ github.event.inputs.date || github.run_id }}"
        git push origin main